# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  vmImageName: 'ubuntu-18.04'
  AZURE_STORAGE_ACCOUNT: 'myreactappsecondary'
  AZURE_CONTAINER_NAME: 'mystoragecontainer' 
  
pool:
  vmImage: ubuntu-18.04

resources:
  pipelines:
  - pipeline: lab3aprimary
    source: ReactAppPrimary-Pipeline
    trigger:
      branches:
      - main
  
stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildReactApp
        displayName: BuildReactApp
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'
                  
          - script: |
              rm -rf node_modules
              yarn install
              yarn cache clean
              yarn run eslint
              yarn build
            displayName: 'Yarn Install and Build'
           
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/build/'
              Contents: |
                $(System.DefaultWorkingDirectory)/build/**/*
              TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
            displayName: 'Copy site files to artifact directory'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/dist'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/react-app-dist.zip
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@0
            displayName: 'Publish site pipeline artifacts'
            inputs:
              artifactName: "react-app-dist"
              targetPath: $(Build.ArtifactStagingDirectory)/react-app-dist.zip

  - stage: Deploy
    displayName: Deploy to Azure Secondary Storage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploySite 
        displayName: Deploy Site to ITE
        environment: 'production'
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@1
                  displayName: 'Download Pipeline Artifacts'
                  inputs:
                    artifactName: "react-app-dist"
                    buildType: 'current'

                - task: ExtractFiles@1
                  inputs:
                    archiveFilePatterns: '$(System.ArtifactsDirectory)/react-app-dist.zip'
                    destinationFolder: '$(System.DefaultWorkingDirectory)/unzip/react-app-dist'
                    cleanDestinationFolder: true

                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'my-react-app-service-connection'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: | 
                      az storage blob delete-batch -s $(AZURE_CONTAINER_NAME) --account-name $(AZURE_STORAGE_ACCOUNT)
                      az storage blob upload-batch -d $(AZURE_CONTAINER_NAME) --account-name "$(AZURE_STORAGE_ACCOUNT)" -s "$(System.DefaultWorkingDirectory)/unzip/react-app-dist/"